<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="RunTests" Id="{3c99bab2-48fb-4f3c-ae2b-1547c32b95ba}" SpecialFunc="None">
    <Declaration><![CDATA[
PROGRAM RunTests
VAR
    fbAtomicMassLookup_Test : FB_AtomicMassLookup_Test;
    fbAtomicNumberLookup_Test : FB_AtomicNumberLookup_Test;
    fbCalculateMassAttenuationCoefficient_Test : FB_CalculateXrayAbsorptionConstant_Test;
    fbCalculateThicknessFromTransmission_Test : FB_CalculateThicknessFromTransmission_Test;
    fbMaterialDensityLookup_Test : FB_MaterialDensityLookup_Test;
    fbScatteringFactorLookupCXRO_Test : FB_ScatteringFactorLookupCXRO_Test;
    fbScatteringFactorLUT_Test : FB_ScatteringFactorLUT_Test;
    fbTestTransmission : FB_TestTransmission;
    fbTestElementDensity : FB_TestElementDensity;
    fbAtomicNumber_Test : FB_AtomicNumber_Test;

    (* Smoke test - just instantiate *)
    fbPhysicalConstants : FB_PhysicalConstants;
    fbAtomicMass : FB_AtomicMass;

END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[
TcUnit.RUN();

fbPhysicalConstants();
fbAtomicMass();
]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>