<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="FB_CalcLREALMock" Id="{bd34b3e8-fd89-4e8a-b12d-4532c72a5f8a}" SpecialFunc="None">
    <Declaration><![CDATA[
FUNCTION_BLOCK FB_CalcLREALMock EXTENDS FB_FallibleMock IMPLEMENTS I_CalcLREAL
VAR
    fResult : LREAL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="Calculate" Id="{8d2db5d4-517a-48a1-b360-7ddccbfcc9d8}">
      <Declaration><![CDATA[
METHOD Calculate : LREAL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[
Calculate := fResult;
]]></ST>
      </Implementation>
    </Method>
    <Method Name="SetResult" Id="{83f2d6c6-eaa9-4112-bf0b-9f218db5e2c1}">
      <Declaration><![CDATA[
METHOD SetResult
VAR_INPUT
    fResult : LREAL;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[
THIS^.fResult := fResult;
]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>